import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "../components/providers";
import ThemeToggle from "../components/themeToggle";

const IranSans = localFont({
  src: [
    {
      path: "../public/fonts/IRANSansX-Thin.woff2",
      weight: "100",
    },
    {
      path: "../public/fonts/IRANSansX-UltraLight.woff2",
      weight: "200",
    },
    {
      path: "../public/fonts/IRANSansX-Light.woff2",
      weight: "300",
    },
    {
      path: "../public/fonts/IRANSansX-Regular.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/IRANSansX-Medium.woff2",
      weight: "500",
    },
    {
      path: "../public/fonts/IRANSansX-DemiBold.woff2",
      weight: "600",
    },
    {
      path: "../public/fonts/IRANSansX-Bold.woff2",
      weight: "700",
    },
    {
      path: "../public/fonts/IRANSansX-ExtraBold.woff2",
      weight: "800",
    },
    {
      path: "../public/fonts/IRANSansX-ExtraBlack.woff2",
      weight: "900",
    },
    {
      path: "../public/fonts/IRANSansX-Black.woff2",
      weight: "950",
    },
  ],
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${IranSans.className} antialiased`}>
        <Providers>
          <ThemeToggle />
          {children}
        </Providers>
      </body>
    </html>
  );
}
